### PR TITLE
Add support for git@ remotes

### PR DESCRIPTION
**Pull request by rwjc**
Adds support remotes with ssh url format git@host:...

### CODE REVIEW

**Comment by kristijanhusak** [comment]
Thanks!

**Comment by iivvoo** [comment]
Are you sure this works? My `git@github.com:SomeOrg/somerepo` now points to https://github.com/git@github.com:SomeOrg/somerepo/...` because, I assume, it doesn't split on the `:`

**Comment by iivvoo** [comment]
Reverting to the commit before this PR was merged,

```
  use {
      'kristijanhusak/vim-create-pr',
       commit="5eab5d706b277e93a6e0775217fc10ecd5b10b25"
  }
```
makes my remotes work properly again.

**Comment by kristijanhusak** [comment]
@iivvoo you are right. I reverted the commit, master should be working fine now.

**Comment by rwjc** [comment]
Sorry about that, all the git repos I used this change with have more than 1 level in their path, e.g. `git@github.com:SomeOrg/somePath/somerepo`. That's why the subscripts worked on the split. If there's only 1 `/` then it won't work. It's also possible for current `ssh://` and `https://` to hit the same problem though, e.g. if you're using a custom git host and say the repo is `https://githost.com/somerepo.git` 

I will see if I can come up with a better solution.

**Pull request merged**
